// Ruumilahenduste mallid ja arhitektuursed moodulid
export const ROOM_MODULES = {
  living_open: {
    id: 'living_open',
    name: 'Avatud elutuba & panoraam-söögituba',
    icon: '🛋️',
    area: 36,
    width: 6.0,
    depth: 6.0,
    desc: 'Avar eluruum maast laeni akendega, nurgadiivani tsooniga ja 6-kohalise söögilauaga.',
    floorMat: 'parquet',
    wallMat: 'plaster',
    wallThick: 0.25,
    openings: [
      { wallIdx: 0, type: 'window', along: 3.0, width: 2.2, height: 2.1, sill: 0.05 }, // Panoraamaken maani tagaseinas
      { wallIdx: 1, type: 'door', along: 2.0, width: 1.4, height: 2.1, sill: 0 },       // Terrassiuks paremal
      { wallIdx: 3, type: 'door', along: 4.5, width: 0.9, height: 2.1, sill: 0 },       // Siseuks vasakul
    ],
    items: [
      { type: 'sofa', rx: -1.6, rz: -0.8, ry: 0 },
      { type: 'coffeeTable', rx: -1.6, rz: 0.6, ry: 0 },
      { type: 'tvConsole', rx: -1.6, rz: 2.4, ry: Math.PI },
      { type: 'rugModern', rx: -1.6, rz: 0.2, ry: 0 },
      { type: 'floorLamp', rx: -2.4, rz: -2.2, ry: 0.4 },
      { type: 'table', rx: 1.6, rz: 0.2, ry: Math.PI / 2 },
      { type: 'diningPendant', rx: 1.6, rz: 0.2, ry: 0 },
      { type: 'indoorPlant', rx: 2.4, rz: -2.3, ry: 0 },
    ],
  },

  kitchen_island: {
    id: 'kitchen_island',
    name: 'Köök köögisaarega & hommikusöögiala',
    icon: '🍳',
    area: 18,
    width: 4.5,
    depth: 4.0,
    desc: 'Kaasaegne köök saarega keskel, kõrgete seadmekappidega ja ergonoomilise töökaugusega.',
    floorMat: 'tile_gray',
    wallMat: 'plaster',
    wallThick: 0.25,
    openings: [
      { wallIdx: 0, type: 'window', along: 2.25, width: 1.6, height: 0.6, sill: 1.5 }, // Ribaaken töölaua kohal
      { wallIdx: 3, type: 'door', along: 2.0, width: 0.9, height: 2.1, sill: 0 },        // Sissepääsuuks
    ],
    items: [
      { type: 'kitchenHighCabinets', rx: 0, rz: -1.4, ry: 0 },
      { type: 'fridge', rx: 1.7, rz: -1.4, ry: 0 },
      { type: 'kitchenUnit', rx: 0, rz: 0.5, ry: 0 },
      { type: 'barStools', rx: 0, rz: 1.3, ry: Math.PI },
      { type: 'diningPendant', rx: 0, rz: 0.5, ry: 0 },
    ],
  },

  master_bed: {
    id: 'master_bed',
    name: 'Master magamistuba garderoobiga',
    icon: '🛏️',
    area: 20,
    width: 5.0,
    depth: 4.0,
    desc: 'Luksuslik magamistuba peatsi ja öökappidega voodi, lükandustega garderoobi ja lugemisnurgaga.',
    floorMat: 'parquet',
    wallMat: 'plaster',
    wallThick: 0.25,
    openings: [
      { wallIdx: 0, type: 'window', along: 2.5, width: 1.4, height: 1.4, sill: 0.85 },
      { wallIdx: 3, type: 'door', along: 3.2, width: 0.9, height: 2.1, sill: 0 },
    ],
    items: [
      { type: 'bedNightstands', rx: -0.8, rz: -0.6, ry: 0 },
      { type: 'wardrobeModern', rx: 1.8, rz: 0.2, ry: -Math.PI / 2 },
      { type: 'armchairNordic', rx: -1.8, rz: 1.2, ry: Math.PI * 0.8 },
      { type: 'dresser', rx: -0.8, rz: 1.5, ry: Math.PI },
      { type: 'indoorPlant', rx: -2.0, rz: -1.4, ry: 0 },
    ],
  },

  sauna_spa: {
    id: 'sauna_spa',
    name: 'Põhjamaine saunakompleks & spaa',
    icon: '🪵',
    area: 16,
    width: 4.0,
    depth: 4.0,
    desc: 'Leiliruum puukerisega, pesuruum dušiga ning eesruum puhketooliga.',
    floorMat: 'tile_gray',
    wallMat: 'wood',
    wallThick: 0.20,
    openings: [
      { wallIdx: 0, type: 'window', along: 1.2, width: 0.6, height: 0.6, sill: 1.4 },
      { wallIdx: 2, type: 'door', along: 2.0, width: 0.9, height: 2.1, sill: 0 },
    ],
    items: [
      { type: 'stove', rx: -1.2, rz: -1.2, ry: 0 },
      { type: 'lavaLong', rx: -0.6, rz: -1.4, ry: 0 },
      { type: 'lavaShort', rx: -0.6, rz: -0.9, ry: 0 },
      { type: 'shower', rx: 1.2, rz: -1.2, ry: 0 },
      { type: 'bathroomVanity', rx: 1.2, rz: 0.8, ry: Math.PI },
      { type: 'towelWarmer', rx: 1.7, rz: -0.2, ry: -Math.PI / 2 },
    ],
  },

  home_office: {
    id: 'home_office',
    name: 'Kodukontor & loovstuudio',
    icon: '💼',
    area: 14,
    width: 4.0,
    depth: 3.5,
    desc: 'Ergonoomiline töökeskkond rohke loomuliku valguse, raamaturiiulite ja lugemistooliga.',
    floorMat: 'parquet',
    wallMat: 'plaster',
    wallThick: 0.20,
    openings: [
      { wallIdx: 0, type: 'window', along: 2.0, width: 1.6, height: 1.3, sill: 0.9 },
      { wallIdx: 2, type: 'door', along: 2.0, width: 0.9, height: 2.1, sill: 0 },
    ],
    items: [
      { type: 'deskOffice', rx: 0, rz: -0.6, ry: 0 },
      { type: 'bookshelf', rx: -1.6, rz: 0.5, ry: Math.PI / 2 },
      { type: 'armchairNordic', rx: 1.2, rz: 0.7, ry: -Math.PI * 0.75 },
      { type: 'rugModern', rx: 0, rz: 0.2, ry: 0 },
      { type: 'floorLamp', rx: 1.4, rz: -1.1, ry: 0 },
      { type: 'indoorPlant', rx: 1.4, rz: 1.1, ry: 0 },
    ],
  },

  luxury_bath: {
    id: 'luxury_bath',
    name: 'Luksuslik vannituba & pesuruum',
    icon: '🛁',
    area: 12,
    width: 3.5,
    depth: 3.5,
    desc: 'Eraldiseisev ovaalvann, dušinurk, lai valamukapp ja integreeritud pesumasin.',
    floorMat: 'tile_gray',
    wallMat: 'plaster',
    wallThick: 0.20,
    openings: [
      { wallIdx: 0, type: 'window', along: 1.75, width: 1.2, height: 0.6, sill: 1.6 },
      { wallIdx: 2, type: 'door', along: 1.75, width: 0.9, height: 2.1, sill: 0 },
    ],
    items: [
      { type: 'bathTub', rx: 0, rz: -1.0, ry: 0 },
      { type: 'shower', rx: -1.0, rz: 1.0, ry: 0 },
      { type: 'bathroomVanity', rx: 1.0, rz: 0.2, ry: -Math.PI / 2 },
      { type: 'toilet', rx: 1.0, rz: 1.1, ry: -Math.PI / 2 },
      { type: 'washingMachine', rx: -1.1, rz: -0.2, ry: Math.PI / 2 },
    ],
  },

  outdoor_terrace: {
    id: 'outdoor_terrace',
    name: 'Puhketerrass & väliköök',
    icon: '☀️',
    area: 24,
    width: 6.0,
    depth: 4.0,
    desc: 'Puitkarkassil kaetud suveterrass roostevaba grilliköögi ja 6-kohalise aialauaga.',
    floorMat: 'paver',
    wallMat: 'wood',
    wallThick: 0.15,
    openings: [],
    items: [
      { type: 'deckModule', rx: 0, rz: 0, ry: 0 },
      { type: 'pergola', rx: 0, rz: 0, ry: 0 },
      { type: 'outdoorKitchen', rx: -1.8, rz: -1.2, ry: 0 },
      { type: 'outdoorTable', rx: 0.8, rz: 0.2, ry: 0 },
      { type: 'daybedOutdoor', rx: -1.8, rz: 1.0, ry: Math.PI / 2 },
    ],
  },
};

// Terviklikud arhitektuursed kujundusstiilid (Design Styles / Aesthetic Palettes)
export const DESIGN_STYLES = {
  nordic_light: {
    id: 'nordic_light',
    name: 'Põhjamaine hele (Nordic Light)',
    icon: '🌿',
    desc: 'Looduslik heledus, soe valge krohv, hele tammeparkett ja mahedad heledad puidutoonid.',
    wallMat: 'plaster',
    floorMat: 'parquet',
    roofMat: 'roof_dark',
    accentColor: '#176b52',
    swatches: ['#f8fafc', '#e2d3be', '#c4a574', '#176b52'],
  },
  warm_contemporary: {
    id: 'warm_contemporary',
    name: 'Moodne tamm & mikrotsement',
    icon: '🏛️',
    desc: 'Harjatud soe tamm, lihvitud betoon ja mikrotsemendist pinnad, peened grafiithallid jooned.',
    wallMat: 'plaster',
    floorMat: 'tile_gray',
    roofMat: 'roof_dark',
    accentColor: '#363c44',
    swatches: ['#ebe8e1', '#767c85', '#b5824c', '#2c353f'],
  },
  japandi_zen: {
    id: 'japandi_zen',
    name: 'Japandi termopuit & kivi',
    icon: '🧘',
    desc: 'Rahu ja harmoonia. Tume termopuit, soojad savikrohvi toonid ja naturaalne kivi.',
    wallMat: 'dark',
    floorMat: 'paver',
    roofMat: 'roof_dark',
    accentColor: '#5a4030',
    swatches: ['#5a4030', '#ded6c8', '#828588', '#2b231c'],
  },
  modern_luxury: {
    id: 'modern_luxury',
    name: 'Kaasaegne luksus & marmor',
    icon: '✨',
    desc: 'Luksuslik hele kiviplaat, tume puitviimistlus ja väärikad arhitektuursed kontrastid.',
    wallMat: 'plaster',
    floorMat: 'tile_gray',
    roofMat: 'roof_dark',
    accentColor: '#8f3c2c',
    swatches: ['#f5f7fa', '#767c85', '#5a4030', '#8f3c2c'],
  },
};
